config/routes.rb
Rails.application.routes.draw do

  resources :race_scores

  root 'welcome#index'
  get 'settings' => 'settings#new'
  post 'settings' => 'settings#create'

  resources :fixtures
  resources :races do
    member do
      get 'score'
    end
  end

  resources :seasons, :clubs, :athletes, :results do
    member do
      get 'delete'
    end
    collection do
      get 'import'
      post 'upload'
    end
  end

end

app/models/club.rb
class Club < ActiveRecord::Base

  include Importable

  validates :name, :abbr, presence: true
  before_save { self.abbr = abbr.to_s.upcase }
  has_and_belongs_to_many :fixtures
  has_many :races, through: :fixtures
  has_many :athletes, dependent: :destroy
  has_many :results
  has_many :race_scores


  scope :alphabetical, -> { order('name ASC') }    
  scope :division, ->(div) { where(division: div) }

  def self.import(file)
    return false unless file && s = import_spreadsheet(file)
    rows = s.parse(headers: true)
    rows[1..s.last_row-1].each do |row|
      # check for changes to name or abbr
      name = find_by_name(row['name'].to_s)
      abbr = find_by_abbr(row['abbr'].to_s)
      # skip if everything is the same
      next if name && abbr && name.division == row['division']
      # use that club if one matches otherwise create a new one
      club = name || abbr
      club ||= new
      club.update_attributes(row)
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :find_club, only: [:edit, :update, :delete, :destroy]
  before_action :find_athletes, only: [:show]

  def index
    @div1 = Club.division(1).alphabetical
    @div2 = Club.division(2).alphabetical
    @others = Club.division(nil).alphabetical
    respond_to do |format|
      format.html
      format.csv { render text: Club.to_csv }
    end
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      flash[:success] = "Club created successfully"
      redirect_to clubs_path
    else
      flash[:alert] = "Errors are present"
      render 'new'
    end
  end

  def update
    if @club.update(club_params)
      flash[:success] = "Club updated successfully"
      redirect_to clubs_path
    else
      flash[:alert] = "Errors are present"
      render 'edit'
    end
  end

  def destroy
    club = @club.destroy
    flash[:notice] = "#{club.name} has been deleted"
    redirect_to clubs_path
  end

  def import    
  end

  def upload
    if Club.import(params[:file])
      flash[:success] = "New clubs imported."
      redirect_to clubs_path
    else
      flash[:alert] = "Invalid file chosen"
      render 'import'
    end
  end

  private

  def club_params
    params.require(:club).permit(:name, :abbr, :contact, :email, :url, :division)
  end

  def find_club
    @club = Club.find(params[:id])
  end

  def find_athletes
    @club = Club.includes(:athletes).find(params[:id])
  end
end

app/views/clubs/_form.html.erb
<%= form_for @club do |f| -%>
  <%= render 'layouts/errors', object: f.object %>
  <div class="field">
    <div class="small-3 columns"><%= f.label :name, "Name", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :name %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :abbr, "Abbreviation", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :abbr %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :contact, "Contact", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :contact %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :email, "Email", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :email %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :url, "Website", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :url %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :division, "Division", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :division %></div>
  </div>
  <div class="field">
    <div class="small-6 columns"><%= f.submit "Submit", :disable_with => 'Submiting...', class: "button large radius" %></div>
    <div class="small-6 columns"><%= link_to "Back", :back, class: "secondary button large radius right" %></div>
  </div> 
<% end -%>

app/views/clubs/_table.html.erb
<% if clubs.any? %>
<table>
  <thead>
    <tr>
      <th width="25%">Name</th>
      <th width="30%">Website</th>
      <th width="25%">Team Manager</th>
      <th width="20%">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% clubs.each do |c| %>
    <tr>
      <td><%= link_to c.name, club_path(c) %></td>
      <td><%= link_to c.url, "http://#{c.url}" %></td>
      <td><%= mail_to c.email, c.contact %></td>
      <td><%= link_to 'Edit', edit_club_path(c), class: "button tiny radius secondary" %> <%= link_to 'Delete',delete_club_path(c), class: "button tiny radius alert"  %> </td>
    </tr>
    <% end %>
  </tbody>    
</table> 
<% else %>
<p>No clubs found</p>
<% end %>

app/views/clubs/delete.html.erb
<%= provide(:title, "Delete club") %>
<h1>Delete club</h1>

<p>Are you sure you want to delete this club from the database?</p>
<h2><%= @club.name %></h2>
<%= link_to "Delete", club_path(@club), method: :delete, class: "alert button radius large" %>

app/views/clubs/edit.html.erb
<%= provide(:title, "Edit club") %>
<div class="push-3 medium-6 columns">
  <h1>Edit club</h1>
  <%= render 'form' %>
</div>

app/views/clubs/import.html.erb
<%= provide(:title, "Import Clubs") %>
<div class="small-12 medium-6 columns small-centred">
  <h1>Import Clubs</h1>
  <p>This form can be used to import a spreadsheet of club data. The data should be listed in columns with the following headings:</p>
  <ul>
    <li>name</li>
    <li>abbr</li>
    <li>contact</li>
    <li>email</li>
    <li>url</li>
    <li>division</li>
  </ul>
  <%= form_tag upload_clubs_path, multipart: true do%>
  <div class="field">
    <div class="small-12 columns"><%= file_field_tag :file %></div>
  </div>   
  <div class="field">
    <div class="small-12 columns">
      <%= submit_tag "Upload", class: "button large radius" %></div>
    </div>
<% end -%>
</div>

app/views/clubs/index.html.erb
<%= provide(:title, "Clubs index") %>
<h1>Clubs Index</h1>
<p>The following clubs are currently in the database:</p>
<p>Download as <%= link_to "CSV", clubs_path(format: 'csv'), class: "button tiny radius" %></p>
<div id="div1">
  <h2>Division 1</h2>
  <%= render 'table', clubs: @div1 %>
</div>
<div id="div2">
  <h2>Division 2</h2>
  <%= render 'table', clubs: @div2 %>  
</div>
<div id="unassigned">
  <h2>Unassigned clubs</h2>
  <%= render 'table', clubs: @others %>
</div>
<%= link_to "Add new club", new_club_path, class: "button radius large" %>
<%= link_to "Import clubs", import_clubs_path, class: "button radius large" %>

app/views/clubs/new.html.erb
<%= provide(:title, "Add club") %>
<div class="push-3 medium-6 columns">
  <h1>Add a new club</h1>
  <%= render 'form' %>
</div>

app/views/clubs/show.html.erb
<%= provide(:title, @club.name) %>
<h1><%= @club.name %> (<%= @club.abbr %>)</h1>

<p>Team contact: <%= @club.contact %></p>
<p>Email: <%= @club.email %></p>
<p>Club website: <%= link_to @club.url, @club.url %></p>
<p>Current division: <%= @club.division %></p>

<%= render 'shared/athlete_table', athletes: @club.athletes %>

<%= link_to "Back", clubs_path, class: "button large secondary radius" %>