config/routes.rb
Rails.application.routes.draw do

  resources :race_scores

  root 'welcome#index'
  get 'settings' => 'settings#new'
  post 'settings' => 'settings#create'

  resources :fixtures
  resources :races do
    member do
      get 'score'
    end
  end

  resources :seasons, :clubs, :athletes, :results do
    member do
      get 'delete'
    end
    collection do
      get 'import'
      post 'upload'
    end
  end

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :fixtures, dependent: :destroy
  has_many :races, through: :fixtures
  has_many :clubs, through: :fixtures

  accepts_nested_attributes_for :fixtures, reject_if: proc { |attributes| attributes['date'].blank? }, allow_destroy: true
  validates :name, presence: true
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :find_season, only: [:show, :edit, :delete, :update, :destroy]
  before_action :check_config, only: [:new, :edit]

  def index
    @seasons = Season.all
  end

  def show
    @fixtures = @season.fixtures
  end

  def new
    @season = Season.new
    CONFIG[:fixtures].times { @season.fixtures.build }
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      flash[:success] = "Season created successfully"

      redirect_to season_path(@season)
    else
      flash[:alert] = "Errors are present"
      render 'new'
    end
  end

  def edit
    (CONFIG[:fixtures]-@season.fixtures.count).times { @season.fixtures.build }
  end

  def update
    if @season.update(season_params)
      flash[:success] = "Season updated successfully"
      redirect_to seasons_path
    else
      flash[:alert] = "Errors are present"
      render 'edit'
    end
  end

  def destroy
    s = @season.destroy
    flash[:notice] = "#{s.name} has been deleted from the database"
    redirect_to seasons_path
  end

  private

  def find_season
    @season = Season.includes(fixtures: [:races, :clubs]).find(params[:id])
  end

  def season_params
    params.require(:season).permit(:name, :fixtures_attributes => [:id, :date, :location, {:club_ids => []}, :_destroy])
  end

  def check_config
    redirect_to settings_path unless CONFIG
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<p>Fill in these fields with the details of the fixtures making up this season. The separate races to be staged at each fixture will be set up automatically from the information in the settings.</p>
<%= form_for @season do |f| -%>
  <%= render 'layouts/errors', object: f.object %>
    <div class="small-1 columns"><%= f.label :name, "Name" %></div>
    <div class="small-4 columns end"><%= f.text_field :name %></div>
    <div class="fixture-fields">
    <%= f.fields_for :fixtures do |b| %>
      <div id="fixture-<%= b.index %>">
        <div class="small-12 medium-6 large-3 columns">
          <div class="row">
            <div class="small-4 columns"><%= b.label :date, class: "inline" %></div>
            <div class="small-8 columns"><%= b.text_field :date, class: "datepicker" %></div>
          </div>
        </div>
        <div class="small-12 medium-6 large-3 columns">
          <div class="row">
            <div class="small-4 columns"><%= b.label :location, "Location", class: "inline" %></div>
            <div class="small-8 columns"><%= b.text_field :location %></div>
          </div>
        </div>
        <div class="small-12 medium-6 large-4 columns">
          <div class="row">
            <div class="small-4 columns"><%= b.label :club_ids, "Host clubs", class: "inline" %></div>
            <div class="small-8 columns"><%= b.collection_select(:club_ids, Club.alphabetical, :id, :name, {}, {multiple: true, size: 5} ) %></div>
          </div>
        </div>
        <div class="small-12 medium-6 large-2 columns">
          <div class="row">
            <div class="small-4 columns"><%= b.label :_destroy, "Remove", class: "inline" %></div>
            <div class="small-8 columns"><%= b.check_box :_destroy %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
    <div class="small-2 columns">
      <%= f.submit "Submit", class: "button radius" %>
    </div>
<% end -%>

app/views/seasons/delete.html.erb
<%= provide(:title, "Delete season") %>
<h1>Delete a season</h1>
<p>Are you sure that you wish to delete this season?</p>
<h2><%= @season.name %></h2>
<p>Any fixtures and races associated with it will also be deleted.</p>
<%= link_to "Confirm Delete", season_path, method: :delete, class: "alert button large radius" %>

app/views/seasons/edit.html.erb
<%= provide(:title, "Edit Season") %>
<h1>Edit Season</h1>

<%= render 'form' %>

app/views/seasons/index.html.erb
<%= provide(:title, "Seasons index") %>
<h1>All Seasons</h1>
<p>The following seasons have been defined:</p>
<% if @seasons.any? %>
  <table>
    <tr>
      <th width="60%">Name</th>
      <th width="20%">Fixtures</th>
      <th width="20%">Actions</th>
    </tr>
    <% @seasons.each do |s| %>
    <tr>
      <td><%= link_to s.name, season_path(s) %></td>
      <td><%= s.fixtures.count %></td>
      <td><%= link_to 'Edit', edit_season_path(s), class: "secondary button tiny radius" %> <%=link_to "Delete", delete_season_path(s), class: "alert button tiny radius" %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <p>No seasons yet</p>
<% end %>

<%= link_to "Add season", new_season_path, class: "button large radius" %>

app/views/seasons/new.html.erb
<%= provide(:title, "Add season") %>
<h1>Add a new season</h1>

<%= render 'form' %>

app/views/seasons/show.html.erb
<h1><%= @season.name %></h1>

<% @fixtures.each_with_index do |f,i| %>
  <p>Fixture <%= i+1 %>: 
  <% if f.date > Date.today %>
    To be held
  <% else %>
    Held
  <% end %>
  on <%= f.date.strftime("%d %B %Y") %> at <%= f.location %>
  <% if f.clubs.any? %>, hosted by <%= f.clubs.length > 1 ? f.clubs.map(&:name).join(' and ') : f.clubs.first.name %>
  <% end %>
  </p>
  <ul>
  <% f.races.each do |r| %>
    <li><%= link_to r.classification, race_path(r) %></li>
  <% end %>    
  </ul>
<% end %>
<%= link_to "Back", :back, class: "secondary large button radius" %>