config/routes.rb
Rails.application.routes.draw do

  resources :race_scores

  root 'welcome#index'
  get 'settings' => 'settings#new'
  post 'settings' => 'settings#create'

  resources :fixtures
  resources :races do
    member do
      get 'score'
    end
  end

  resources :seasons, :clubs, :athletes, :results do
    member do
      get 'delete'
    end
    collection do
      get 'import'
      post 'upload'
    end
  end

end

app/models/athlete.rb
 class Athlete < ActiveRecord::Base
  include Importable

  belongs_to :club
  has_many :results
  has_many :races, through: :results

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    full_name = first_name + ' ' + last_name
    if second_claim?
      full_name = full_name + ' *'
    end
    return full_name
  end

  def age(date)
    ((date - self.dob)/365.23).to_i
  end

  def second_claim?
    self.second_claim
  end

  def category(date)
    return "n/a" unless self.dob?
    age = self.age(date)
    case
      when age > 35 #veterans
        rnd_age = (self.age(date)/5).to_i*5
        return 'V'+rnd_age.to_s
      when age >= 20 #seniors
        return 'Sen'
      else
        if date.end_of_year - 121 > date #if date is before 1st Sept
          age = self.age(date.beginning_of_year - 123) #returns age on last 31st Aug
        else
          age = self.age(date.end_of_year - 122) #returns age on 1st Sept
        end
        case age
          when 0..12
            'U13'            
          when 13,14
            'U15'
          when 15, 16
            'U17'
          else
            'U20'
        end
    end
  end

  def self.import(file)
    return false unless file && s = import_spreadsheet(file)
    rows = s.parse(headers: true, clean: true)
    rows[1..s.last_row-1].each do |row|
      if row['name']
        split_names = row['name'].partition(" ")
        first_name = split_names[0]
        last_name = split_names[2]
      elsif row['first_name'] && row['last_name']
        first_name = row['first_name']
        last_name = row['last_name']
      else
        next
      end
      club = Club.find_by_abbr(row['club'])
      club_id = club ? club.id : nil
      athlete = find(row['id']) if row['id']
      athlete ||= where(first_name: first_name, dob: row['dob'])
      athlete = athlete.size >= 1 ? athlete.select{ |a| a.last_name == last_name }.first : nil
      athlete ||= new
      athlete.update_attributes(first_name: first_name, last_name: last_name, dob: row['dob'], bib: row['bib'], club_id: club_id, second_claim: row['second_claim'])
    end
  end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :find_athlete, only: [:show, :edit, :delete, :update, :destroy]

  def new
    @athlete = Athlete.new
  end

  def show
    @athlete = Athlete.includes(:club, results: [:fixture]).limit(10).find(params[:id])
  end

  def create
    @athlete = Athlete.new(athlete_params)
    if @athlete.save
      flash[:success] = "Athlete added successfully"
      redirect_to athletes_path
    else
      flash[:alert] = "Errors are present"
      render 'new'
    end
  end

  def index
    respond_to do |format|
      format.html { @athletes = Athlete.order('last_name ASC').paginate(page: params[:page]) }
      format.csv { render text: Athlete.to_csv }      
    end
  end

  def edit
    session[:return_to] ||= request.referer
  end

  def update
    if @athlete.update(athlete_params)
      flash[:success] = "Athlete update successfully"
      redirect_to session.delete(:return_to) || :back
    else
      flash[:alert] = "Errors are present"
      render 'edit'
    end
  end

  def delete
    session[:return_to] ||= request.referer
  end

  def destroy
    a = @athlete.destroy
    flash[:notice] = "#{a.full_name} has been deleted"
    redirect_to session.delete(:return_to)
  end

  def upload
    if Athlete.import(params[:file])
      flash[:success] = "New athletes imported."
      redirect_to athletes_path
    else
      flash[:alert] = "Invalid file chosen"
      render 'import'
    end
  end

  private

  def athlete_params
    params.require(:athlete).permit(:first_name, :last_name, :dob, :club_id, :bib, :second_claim)
  end

  def find_athlete
    @athlete = Athlete.find(params[:id])
  end
end

app/views/athletes/_form.html.erb
<%= form_for @athlete do |f| -%>
  <%= render 'layouts/errors', object: f.object %>
  <div class="field">
    <div class="small-3 columns"><%= f.label :first_name, "First Name", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :first_name %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :last_name, "Last Name", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :last_name %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :dob, "Date of birth", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :dob, class: "datepicker" %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :bib, "Race bib", class: "inline" %></div>
    <div class="small-9 columns"><%= f.text_field :bib %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :club_id, "Club", class: "inline"  %></div>
    <div class="small-9 columns"><%= f.collection_select(:club_id, Club.all, :id, :name) %></div>
  </div>
  <div class="field">
    <div class="small-3 columns"><%= f.label :second_claim, class: "inline" %></div>
    <div class="small-1 columns end"><%= f.check_box :second_claim %></div>
  </div>
  <div class="field">
     <div class="small-6 columns"><%= f.submit "Submit", :disable_with => 'Submiting...', class: "button large radius" %></div>
    <div class="small-6 columns"><%= link_to "Back", :back, class: "secondary button large radius right" %></div>
  </div>
<% end -%>

app/views/athletes/delete.html.erb
<%= provide(:title, "Delete Athlete") %>
<h1>Delete Athlete</h1>
<p>Are you sure you wish to delete this athlete?</p>
<h2><%= @athlete.full_name %></h2>
<%= link_to "Delete", athlete_path, method: :delete, class: "alert button radius large" %>

app/views/athletes/edit.html.erb
<%= provide(:title, "Edit athlete") %>
<div class="push-3 medium-6 columns">
  <h1>Edit Athlete</h1>
  <%= render 'form' %>
</div>

app/views/athletes/import.html.erb
<%= provide(:title, "Import Athletes") %>
<div class="small-12 medium-6 columns small-centred">
  <h1>Import Athletes</h1>
  <p>This form can be used to import a spreadsheet of athlete declarations data. The data should be listed in columns with the following headings:</p>
  <ul>
    <li>id</li>
    <li>first_name</li>
    <li>last_name</li>
    <li>dob</li>
    <li>club abbreviation</li>
    <li>bib</li>
  </ul>
  <%= form_tag upload_athletes_path, multipart: true do%>
  <div class="field">
    <div class="small-12 columns"><%= file_field_tag :file %></div>
  </div>   
  <div class="field">
    <div class="small-12 columns">
      <%= submit_tag "Upload", class: "button large radius" %></div>
    </div>
<% end -%>
</div>

app/views/athletes/index.html.erb
<%= provide(:title, "Athletes Index") %>
<h1>Athletes Index</h1>
<p>There are <%= pluralize(@athletes.count, "athlete") %> in the database</p>
<%= will_paginate @athletes %>
<% if @athletes.any? %>
  <%= render 'shared/athlete_table', athletes: @athletes %>
<% end %>
<%= will_paginate @athletes %>
<%= link_to "Add an athlete", new_athlete_path, class: "button radius large" %>
<%= link_to "Import athletes", import_athletes_path, class: "button radius large" %>

app/views/athletes/new.html.erb
<%= provide(:title, "New Athlete") %>
<div class="push-3 medium-6 columns">
  <h1>Add Athlete</h1>
  <%= render 'form' %>
</div>

app/views/athletes/show.html.erb
<%= provide(:title, "#{@athlete.full_name}".html_safe) %>
<div class="medium-6 columns small-centred">
  <h1><%= @athlete.full_name %></h1>
  <div class="field">
    <div class="small-4 columns"><p>Club</p></div>
    <div class="small-8 columns">
      <p><%= @athlete.club.name %>&nbsp;<% if @athlete.second_claim? %><small>(Second claim)</small><% end %></p></div>
  </div>
  <div class="field">
    <div class="small-4 columns"><p>Category</p></div>
    <div class="small-8 columns"><p><%= @athlete.category(Date.today) %></p></div>
  </div>
<p>The results of the last 10 races for this person will be displayed below :-)</p>
</div>
<div class="large-12 columns">
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Location</th>
        <th>Time</th>
        <th>Position</th>
        <th>Category</th>
      </tr>
    </thead>
    <tbody>
    <% @athlete.results.each do |r| %>
      <tr>
        <td><%= r.fixture.date %></td>
        <td><%= r.fixture.location %></td>
        <td><%= r.formatted_time %></td>
        <td><%= r.position %></td>
        <td><%= r.category %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>