config/routes.rb
Rails.application.routes.draw do

  resources :race_scores

  root 'welcome#index'
  get 'settings' => 'settings#new'
  post 'settings' => 'settings#create'

  resources :fixtures
  resources :races do
    member do
      get 'score'
    end
  end

  resources :seasons, :clubs, :athletes, :results do
    member do
      get 'delete'
    end
    collection do
      get 'import'
      post 'upload'
    end
  end

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      <strong>The form contained <%= pluralize(object.errors.count, "error") %>.</strong>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="alert-box <%= type %> radius" data-alert>
      <%= msg %>
      <a href="" class="close">×</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">&copy; Surrey Ladies Cross-Country League <%= Date.today.strftime("%Y") %></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <li><%= link_to 'Contact', '#' %></li>
        <li><%= link_to 'About', '#' %></li>
        <li><%= link_to 'Help', '#' %></li>
      </ul>
    </section>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'Logo', root_path, id: "logo" %></h1>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#">
            <span>Menu</span>
          </a>
        </li>
      </ul>
  
      <section class="top-bar-section">
        <ul class="right">
          <li><%= link_to 'Seasons', seasons_path %></li>
          <li><%= link_to 'Athletes', athletes_path %></li>
          <li><%= link_to 'Clubs', clubs_path %></li>
        </ul>
      </section>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="page-wrap">
      <%= render 'layouts/header' %>
      <div class="row">
        <%= render 'layouts/flash' %>
        <%= yield %>
        <% if Rails.env.development? %>
        <div class="params small-12 columns"><%= debug(params) %></div>
        <% end %>
      </div>
  </div>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>